// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import LocationController from "./location_controller"
// import Select2Controller from 'stimulus-select2'

import NotificationsController from "./notifications_controller"

application.register("location", LocationController)
application.register('notifications', NotificationsController)
// application.register("select2", Select2Controller)