version: "3"
services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: admin
      POSTGRES_DB: storage
    ports:
      - "5432:5432"
  app:
    container_name: storage_app
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
